### PR TITLE
Fix filter activation on nginx >= 1.10.1

### PR DESCRIPTION
**Pull request by zyegfryed**
The nginx module type should be `HTTP_FILTER` instead of `HTTP`.

### CODE REVIEW

**Comment by tsuyoshizawa** [comment]
Thank you.
We will check your patch :)

**Comment by tsuyoshizawa** [comment]
We confirmed this patch works fine.
Thank you for your PR.

**Comment by zyegfryed** [comment]
Thanks for sharing the module!
BTW, what do you think about tagging the code so we can use the release/download section for version management?

**Comment by dataich** [comment]
@zyegfryed  Thanks, I added releases!

https://github.com/nulab/nginx-length-hiding-filter-module/releases

**Comment by zyegfryed** [comment]
You rock! 🍰

**Pull request merged**
